name: Deploy Carousel to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Decode GitHub App Private Key
        run: echo "${{ secrets.APP_PRIVATE_KEY }}" | base64 --decode > private-key.pem

      - name: Authenticate with GitHub App
        uses: tibdex/github-app-token@v1
        id: app-auth
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Pull Latest Carousel File
        run: |
          curl -o carousel.html "YOUR_GENERATED_CAROUSEL_FILE_URL"

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ steps.app-auth.outputs.token }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add carousel.html
          git commit -m "Update carousel.html"
          git push origin main
