name: Update Carousel HTML
on:
  workflow_dispatch:
    inputs:
      file_content:
        description: 'Base64 encoded content of carousel.html'
        required: true
      commit_message:
        description: 'Commit message'
        required: true

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Decode and Write carousel.html
        run: echo "${{ inputs.file_content }}" | base64 --decode > carousel.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add carousel.html
          git commit -m "${{ inputs.commit_message }}"
          git push
